language: go

go:
- 1.13.6

sudo: false
  
install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

before_script:
  - go vet ./...
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  
script: 
  - golangci-lint run
  - go test -v ./...
  
notifications:
  slack: pitakaworkspace:8Pde05x9c4PsdXHp6nWaZMCY