language: go
go:
- 1.13.6
sudo: false
install:
- export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
- export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
before_script:
- go get github.com/axw/gocov/gocov
- go vet ./...
- go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- golangci-lint run
- go test -v ./... -covermode=count -coverprofile=coverage.out
- goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

notifications:
  slack: pitakaworkspace:8Pde05x9c4PsdXHp6nWaZMCY
  webhooks: https://coveralls.io/webhook
  
env:
  global:
    secure: Op+/CRhrBXvSS3zohSFec2hO6zkdQ7afjmu6S6x285IRbmQv3HqxvO3JYW7O1dkPmiduoTWo6aR6kVxRFWii0tY+7lLVxQnpd08aUfkcZhHoG9Sih/B2kMWHWjtNFtaMqLzx/O/orQ0VsVqJHTkMCP+K5NDuNxNfnj/8CSS52/wSG8BsL9cvqpoSTiNqAMtUPpJWe0X8qMj6yHESIy/Shn6dKiihveJ01/ffHj8cdPzmV8nGkA13zTWyKQyYqi0i77q+ikNRFvEOllYbSScdegZu5qjsixHaqvCHTcspqk+LuDDWmPa9lcdgyyt07XKMsyeHmbWF2/kqreFJFEWaanp4iupUQXxmnIYMj1GRzVyQWUF2KrktTKDifnWbrJzV+DE+5lLT4BHsiWOrylUzWYRUFEY2+XLLbVAhB4I/zP9lUhztY7DAcBiuRPFaXJxL9wrBccmAwYfVEKjTR6bzcsEHpuTYs5G0/apLRfjlrRePcSZohuZM+KcIz2e5LTw0GvXIZ092MNQJdBj0XKvqertLy2YsXdGkK1RvHYIExYQRrT0yMZ0TM0P/1fKTGh6CQcuocpHIT6D6lj97roI0vyjC3mNFMBwYLu2nh7cI11dNxzIssdMcUbuiyjULFdDmAGUDyFyf8mnno1qOBdRU5TfVcd56ScJNNeRGiIgMwd4=
