language: go
go:
- 1.12.16
sudo: false
before_install:
  - GLIDE_OS_ARCH=`go env GOHOSTOS`-`go env GOHOSTARCH`
  - GLIDE_TAG=$(curl -s https://glide.sh/version)
  - GLIDE_LATEST_RELEASE_URL="https://github.com/Masterminds/glide/releases/download/${GLIDE_TAG}/glide-${GLIDE_TAG}-${GLIDE_OS_ARCH}.tar.gz"
  - wget ${GLIDE_LATEST_RELEASE_URL} -O /tmp/glide.tar.gz
  - mkdir /tmp/glide
  - tar --directory=/tmp/glide -xvf /tmp/glide.tar.gz
  - export PATH=$PATH:/tmp/glide/${GLIDE_OS_ARCH}
install:
- export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
- export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
before_script:
- glide install
- go get github.com/axw/gocov/gocov
- go env GOPATH
- ls
- go vet ./...
- go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- golangci-lint run
- go test -v ./src/... -covermode=count -coverprofile=coverage.out
- goveralls -coverprofile=coverage.out -service=travis-ci
notifications:
  slack: pitakaworkspace:8Pde05x9c4PsdXHp6nWaZMCY
  webhooks: https://coveralls.io/webhook
